# acessidoc/services/voices_catalog.py
from __future__ import annotations
import json
from pathlib import Path
from typing import List, Dict, Optional

# Opcional: caminho para um JSON com TODAS as vozes
VOICES_JSON_PATH = Path(__file__).parent / "voices.json"

# Fallback: algumas vozes só como exemplo (adicione mais se quiser manter tudo em Python)
STATIC_VOICES: List[Dict] = [
    {"shortName": "af-ZA-AdriNeural",     "displayName": "Adri Neural",         "locale": "af-ZA",        "gender": "Female"},
    {"shortName": "af-ZA-WillemNeural",   "displayName": "Willem Neural",       "locale": "af-ZA",        "gender": "Male"},
    {"shortName": "sq-AL-AnilaNeural",    "displayName": "Anila Neural",        "locale": "sq-AL",        "gender": "Female"},
    {"shortName": "sq-AL-IlirNeural",     "displayName": "Ilir Neural",         "locale": "sq-AL",        "gender": "Male"},
    {"shortName": "am-ET-AmehaNeural",    "displayName": "Ameha Neural",        "locale": "am-ET",        "gender": "Male"},
    {"shortName": "am-ET-MekdesNeural",   "displayName": "Mekdes Neural",       "locale": "am-ET",        "gender": "Female"},
    {"shortName": "ar-DZ-AminaNeural",    "displayName": "Amina Neural",        "locale": "ar-DZ",        "gender": "Female"},
    {"shortName": "ar-DZ-IsmaelNeural",   "displayName": "Ismael Neural",       "locale": "ar-DZ",        "gender": "Male"},
    {"shortName": "ar-BH-AliNeural",      "displayName": "Ali Neural",          "locale": "ar-BH",        "gender": "Male"},
    {"shortName": "ar-BH-LailaNeural",    "displayName": "Laila Neural",        "locale": "ar-BH",        "gender": "Female"},
    {"shortName": "ar-EG-SalmaNeural",    "displayName": "Salma Neural",        "locale": "ar-EG",        "gender": "Female"},
    {"shortName": "ar-EG-ShakirNeural",   "displayName": "Shakir Neural",       "locale": "ar-EG",        "gender": "Male"},
    {"shortName": "ar-IQ-BasselNeural",   "displayName": "Bassel Neural",       "locale": "ar-IQ",        "gender": "Male"},
    {"shortName": "ar-IQ-RanaNeural",     "displayName": "Rana Neural",         "locale": "ar-IQ",        "gender": "Female"},
    {"shortName": "ar-JO-SanaNeural",     "displayName": "Sana Neural",         "locale": "ar-JO",        "gender": "Female"},
    {"shortName": "ar-JO-TaimNeural",     "displayName": "Taim Neural",         "locale": "ar-JO",        "gender": "Male"},
    {"shortName": "ar-KW-FahedNeural",    "displayName": "Fahed Neural",        "locale": "ar-KW",        "gender": "Male"},
    {"shortName": "ar-KW-NouraNeural",    "displayName": "Noura Neural",        "locale": "ar-KW",        "gender": "Female"},
    {"shortName": "ar-LB-LaylaNeural",    "displayName": "Layla Neural",        "locale": "ar-LB",        "gender": "Female"},
    {"shortName": "ar-LB-RamiNeural",     "displayName": "Rami Neural",         "locale": "ar-LB",        "gender": "Male"},
    {"shortName": "ar-LY-ImanNeural",     "displayName": "Iman Neural",         "locale": "ar-LY",        "gender": "Female"},
    {"shortName": "ar-LY-OmarNeural",     "displayName": "Omar Neural",         "locale": "ar-LY",        "gender": "Male"},
    {"shortName": "ar-MA-JamalNeural",    "displayName": "Jamal Neural",        "locale": "ar-MA",        "gender": "Male"},
    {"shortName": "ar-MA-MounaNeural",    "displayName": "Mouna Neural",        "locale": "ar-MA",        "gender": "Female"},
    {"shortName": "ar-OM-AbdullahNeural", "displayName": "Abdullah Neural",     "locale": "ar-OM",        "gender": "Male"},
    {"shortName": "ar-OM-AyshaNeural",    "displayName": "Aysha Neural",        "locale": "ar-OM",        "gender": "Female"},
    {"shortName": "ar-QA-AmalNeural",     "displayName": "Amal Neural",         "locale": "ar-QA",        "gender": "Female"},
    {"shortName": "ar-QA-MoazNeural",     "displayName": "Moaz Neural",         "locale": "ar-QA",        "gender": "Male"},
    {"shortName": "ar-SA-HamedNeural",    "displayName": "Hamed Neural",        "locale": "ar-SA",        "gender": "Male"},
    {"shortName": "ar-SA-ZariyahNeural",  "displayName": "Zariyah Neural",      "locale": "ar-SA",        "gender": "Female"},
    {"shortName": "ar-SY-AmanyNeural",    "displayName": "Amany Neural",        "locale": "ar-SY",        "gender": "Female"},
    {"shortName": "ar-SY-LaithNeural",    "displayName": "Laith Neural",        "locale": "ar-SY",        "gender": "Male"},
    {"shortName": "ar-TN-HediNeural",     "displayName": "Hedi Neural",         "locale": "ar-TN",        "gender": "Male"},
    {"shortName": "ar-TN-ReemNeural",     "displayName": "Reem Neural",         "locale": "ar-TN",        "gender": "Female"},
    {"shortName": "ar-AE-FatimaNeural",   "displayName": "Fatima Neural",       "locale": "ar-AE",        "gender": "Female"},
    {"shortName": "ar-AE-HamdanNeural",   "displayName": "Hamdan Neural",       "locale": "ar-AE",        "gender": "Male"},
    {"shortName": "ar-YE-MaryamNeural",   "displayName": "Maryam Neural",       "locale": "ar-YE",        "gender": "Female"},
    {"shortName": "ar-YE-SalehNeural",    "displayName": "Saleh Neural",        "locale": "ar-YE",        "gender": "Male"},
    {"shortName": "az-AZ-BabekNeural",    "displayName": "Babek Neural",        "locale": "az-AZ",        "gender": "Male"},
    {"shortName": "az-AZ-BanuNeural",     "displayName": "Banu Neural",         "locale": "az-AZ",        "gender": "Female"},
    {"shortName": "bn-BD-NabanitaNeural", "displayName": "Nabanita Neural",     "locale": "bn-BD",        "gender": "Female"},
    {"shortName": "bn-BD-PradeepNeural",  "displayName": "Pradeep Neural",      "locale": "bn-BD",        "gender": "Male"},
    {"shortName": "bn-IN-BashkarNeural",  "displayName": "Bashkar Neural",      "locale": "bn-IN",        "gender": "Male"},
    {"shortName": "bn-IN-TanishaaNeural", "displayName": "Tanishaa Neural",     "locale": "bn-IN",        "gender": "Female"},
    {"shortName": "bs-BA-GoranNeural",    "displayName": "Goran Neural",        "locale": "bs-BA",        "gender": "Male"},
    {"shortName": "bs-BA-VesnaNeural",    "displayName": "Vesna Neural",        "locale": "bs-BA",        "gender": "Female"},
    {"shortName": "bg-BG-BorislavNeural", "displayName": "Borislav Neural",     "locale": "bg-BG",        "gender": "Male"},
    {"shortName": "bg-BG-KalinaNeural",   "displayName": "Kalina Neural",       "locale": "bg-BG",        "gender": "Female"},
    {"shortName": "my-MM-NilarNeural",    "displayName": "Nilar Neural",        "locale": "my-MM",        "gender": "Female"},
    {"shortName": "my-MM-ThihaNeural",    "displayName": "Thiha Neural",        "locale": "my-MM",        "gender": "Male"},
    {"shortName": "ca-ES-EnricNeural",    "displayName": "Enric Neural",        "locale": "ca-ES",        "gender": "Male"},
    {"shortName": "ca-ES-JoanaNeural",    "displayName": "Joana Neural",        "locale": "ca-ES",        "gender": "Female"},
    {"shortName": "zh-HK-HiuGaaiNeural",  "displayName": "HiuGaai Neural",      "locale": "zh-HK",        "gender": "Female"},
    {"shortName": "zh-HK-HiuMaanNeural",  "displayName": "HiuMaan Neural",      "locale": "zh-HK",        "gender": "Female"},
    {"shortName": "zh-HK-WanLungNeural", "displayName": "WanLung Neural",      "locale": "zh-HK",        "gender": "Male"},
    {"shortName": "zh-CN-XiaoxiaoNeural","displayName": "Xiaoxiao Neural",     "locale": "zh-CN",        "gender": "Female"},
    {"shortName": "zh-CN-XiaoyiNeural",  "displayName": "Xiaoyi Neural",       "locale": "zh-CN",        "gender": "Female"},
    {"shortName": "zh-CN-YunjianNeural", "displayName": "Yunjian Neural",      "locale": "zh-CN",        "gender": "Male"},
    {"shortName": "zh-CN-YunxiNeural",   "displayName": "Yunxi Neural",        "locale": "zh-CN",        "gender": "Male"},
    {"shortName": "zh-CN-YunxiaNeural",  "displayName": "Yunxia Neural",       "locale": "zh-CN",        "gender": "Male"},
    {"shortName": "zh-CN-YunyangNeural", "displayName": "Yunyang Neural",      "locale": "zh-CN",        "gender": "Male"},
    {"shortName": "zh-CN-liaoning-XiaobeiNeural","displayName":"Xiaobei Neural","locale":"zh-CN-liaoning","gender":"Female"},
    {"shortName": "zh-TW-HsiaoChenNeural","displayName":"HsiaoChen Neural","locale":"zh-TW","gender":"Female"},
    {"shortName": "zh-TW-YunJheNeural",  "displayName": "YunJhe Neural",       "locale": "zh-TW",        "gender": "Male"},
    {"shortName": "zh-TW-HsiaoYuNeural", "displayName": "HsiaoYu Neural",      "locale": "zh-TW",        "gender": "Female"},
    {"shortName": "zh-CN-shaanxi-XiaoniNeural","displayName":"Xiaoni Neural","locale":"zh-CN-shaanxi","gender":"Female"},
    {"shortName": "hr-HR-GabrijelaNeural","displayName":"Gabrijela Neural","locale":"hr-HR","gender":"Female"},
    {"shortName": "hr-HR-SreckoNeural",  "displayName": "Srecko Neural",       "locale": "hr-HR",        "gender": "Male"},
    {"shortName": "cs-CZ-AntoninNeural","displayName":"Antonin Neural","locale":"cs-CZ","gender":"Male"},
    {"shortName": "cs-CZ-VlastaNeural",  "displayName": "Vlasta Neural",       "locale": "cs-CZ",        "gender": "Female"},
    {"shortName": "da-DK-ChristelNeural","displayName":"Christel Neural","locale":"da-DK","gender":"Female"},
    {"shortName": "da-DK-JeppeNeural",   "displayName": "Jeppe Neural",        "locale": "da-DK",        "gender": "Male"},
    {"shortName": "nl-BE-ArnaudNeural",  "displayName": "Arnaud Neural",       "locale": "nl-BE",        "gender": "Male"},
    {"shortName": "nl-BE-DenaNeural",    "displayName": "Dena Neural",         "locale": "nl-BE",        "gender": "Female"},
    {"shortName": "nl-NL-ColetteNeural", "displayName": "Colette Neural",      "locale": "nl-NL",        "gender": "Female"},
    {"shortName": "nl-NL-FennaNeural",   "displayName": "Fenna Neural",        "locale": "nl-NL",        "gender": "Female"},
    {"shortName": "nl-NL-MaartenNeural", "displayName": "Maarten Neural",      "locale": "nl-NL",        "gender": "Male"},
    {"shortName": "en-AU-NatashaNeural", "displayName": "Natasha Neural",      "locale": "en-AU",        "gender": "Female"},
    {"shortName": "en-AU-WilliamNeural", "displayName": "William Neural",      "locale": "en-AU",        "gender": "Male"},
    {"shortName": "en-CA-ClaraNeural",   "displayName": "Clara Neural",        "locale": "en-CA",        "gender": "Female"},
    {"shortName": "en-CA-LiamNeural",    "displayName": "Liam Neural",         "locale": "en-CA",        "gender": "Male"},
    {"shortName": "en-HK-SamNeural",     "displayName": "Sam Neural",          "locale": "en-HK",        "gender": "Male"},
    {"shortName": "en-HK-YanNeural",     "displayName": "Yan Neural",          "locale": "en-HK",        "gender": "Female"},
    {"shortName": "en-IN-NeerjaNeural",  "displayName": "Neerja Neural",       "locale": "en-IN",        "gender": "Female"},
    {"shortName": "en-IN-PrabhatNeural", "displayName": "Prabhat Neural",      "locale": "en-IN",        "gender": "Male"},
    {"shortName": "en-IE-ConnorNeural",  "displayName": "Connor Neural",       "locale": "en-IE",        "gender": "Male"},
    {"shortName": "en-IE-EmilyNeural",   "displayName": "Emily Neural",        "locale": "en-IE",        "gender": "Female"},
    {"shortName": "en-KE-AsiliaNeural",  "displayName": "Asilia Neural",       "locale": "en-KE",        "gender": "Female"},
    {"shortName": "en-KE-ChilembaNeural","displayName":"Chilemba Neural",    "locale":"en-KE","gender":"Male"},
    {"shortName": "en-NZ-MitchellNeural","displayName":"Mitchell Neural",    "locale":"en-NZ","gender":"Male"},
    {"shortName": "en-NZ-MollyNeural",  "displayName": "Molly Neural",        "locale": "en-NZ",        "gender": "Female"},
    {"shortName": "en-NG-AbeoNeural",    "displayName": "Abeo Neural",         "locale": "en-NG",        "gender": "Male"},
    {"shortName": "en-NG-EzinneNeural",  "displayName": "Ezinne Neural",       "locale": "en-NG",        "gender": "Female"},
    {"shortName": "en-PH-JamesNeural",   "displayName": "James Neural",        "locale": "en-PH",        "gender": "Male"},
    {"shortName": "en-PH-RosaNeural",    "displayName": "Rosa Neural",         "locale": "en-PH",        "gender": "Female"},
    {"shortName": "en-SG-LunaNeural",    "displayName": "Luna Neural",         "locale": "en-SG",        "gender": "Female"},
    {"shortName": "en-SG-WayneNeural",   "displayName": "Wayne Neural",        "locale": "en-SG",        "gender": "Male"},
    {"shortName": "en-ZA-LeahNeural",    "displayName": "Leah Neural",         "locale": "en-ZA",        "gender": "Female"},
    {"shortName": "en-ZA-LukeNeural",    "displayName": "Luke Neural",         "locale": "en-ZA",        "gender": "Male"},
    {"shortName": "en-TZ-ElimuNeural",   "displayName": "Elimu Neural",        "locale": "en-TZ",        "gender": "Male"},
    {"shortName": "en-TZ-ImaniNeural",   "displayName": "Imani Neural",        "locale": "en-TZ",        "gender": "Female"},
    {"shortName": "en-GB-LibbyNeural",   "displayName": "Libby Neural",        "locale": "en-GB",        "gender": "Female"},
    {"shortName": "en-GB-MaisieNeural",  "displayName": "Maisie Neural",       "locale": "en-GB",        "gender": "Female"},
    {"shortName": "en-GB-RyanNeural",    "displayName": "Ryan Neural",         "locale": "en-GB",        "gender": "Male"},
    {"shortName": "en-GB-SoniaNeural",   "displayName": "Sonia Neural",        "locale": "en-GB",        "gender": "Female"},
    {"shortName": "en-GB-ThomasNeural",  "displayName": "Thomas Neural",       "locale": "en-GB",        "gender": "Male"},
    {"shortName": "en-US-AriaNeural",           "displayName": "Aria Neural",                "locale": "en-US", "gender": "Female"},
    {"shortName": "en-US-AnaNeural",            "displayName": "Ana Neural",                 "locale": "en-US", "gender": "Female"},
    {"shortName": "en-US-ChristopherNeural",    "displayName": "Christopher Neural",         "locale": "en-US", "gender": "Male"},
    {"shortName": "en-US-EricNeural",           "displayName": "Eric Neural",                "locale": "en-US", "gender": "Male"},
    {"shortName": "en-US-GuyNeural",            "displayName": "Guy Neural",                 "locale": "en-US", "gender": "Male"},
    {"shortName": "en-US-JennyNeural",          "displayName": "Jenny Neural",               "locale": "en-US", "gender": "Female"},
    {"shortName": "en-US-MichelleNeural",       "displayName": "Michelle Neural",            "locale": "en-US", "gender": "Female"},
    {"shortName": "en-US-RogerNeural",          "displayName": "Roger Neural",               "locale": "en-US", "gender": "Male"},
    {"shortName": "en-US-SteffanNeural",        "displayName": "Steffan Neural",             "locale": "en-US", "gender": "Male"},
    {"shortName": "et-EE-AnuNeural",            "displayName": "Anu Neural",                 "locale": "et-EE", "gender": "Female"},
    {"shortName": "et-EE-KertNeural",           "displayName": "Kert Neural",                "locale": "et-EE", "gender": "Male"},
    {"shortName": "fil-PH-AngeloNeural",        "displayName": "Angelo Neural",              "locale": "fil-PH", "gender": "Male"},
    {"shortName": "fil-PH-BlessicaNeural",      "displayName": "Blessica Neural",            "locale": "fil-PH", "gender": "Female"},
    {"shortName": "fi-FI-HarriNeural",          "displayName": "Harri Neural",               "locale": "fi-FI", "gender": "Male"},
    {"shortName": "fi-FI-NooraNeural",          "displayName": "Noora Neural",               "locale": "fi-FI", "gender": "Female"},
    {"shortName": "fr-BE-CharlineNeural",       "displayName": "Charline Neural",            "locale": "fr-BE", "gender": "Female"},
    {"shortName": "fr-BE-GerardNeural",         "displayName": "Gerard Neural",              "locale": "fr-BE", "gender": "Male"},
    {"shortName": "fr-CA-AntoineNeural",        "displayName": "Antoine Neural",             "locale": "fr-CA", "gender": "Male"},
    {"shortName": "fr-CA-JeanNeural",           "displayName": "Jean Neural",                "locale": "fr-CA", "gender": "Male"},
    {"shortName": "fr-CA-SylvieNeural",         "displayName": "Sylvie Neural",              "locale": "fr-CA", "gender": "Female"},
    {"shortName": "fr-FR-DeniseNeural",         "displayName": "Denise Neural",              "locale": "fr-FR", "gender": "Female"},
    {"shortName": "fr-FR-EloiseNeural",         "displayName": "Eloise Neural",              "locale": "fr-FR", "gender": "Female"},
    {"shortName": "fr-FR-HenriNeural",          "displayName": "Henri Neural",               "locale": "fr-FR", "gender": "Male"},
    {"shortName": "fr-CH-ArianeNeural",         "displayName": "Ariane Neural",              "locale": "fr-CH", "gender": "Female"},
    {"shortName": "fr-CH-FabriceNeural",        "displayName": "Fabrice Neural",             "locale": "fr-CH", "gender": "Male"},
    {"shortName": "gl-ES-RoiNeural",            "displayName": "Roi Neural",                 "locale": "gl-ES", "gender": "Male"},
    {"shortName": "gl-ES-SabelaNeural",         "displayName": "Sabela Neural",              "locale": "gl-ES", "gender": "Female"},
    {"shortName": "ka-GE-EkaNeural",            "displayName": "Eka Neural",                 "locale": "ka-GE", "gender": "Female"},
    {"shortName": "ka-GE-GiorgiNeural",         "displayName": "Giorgi Neural",              "locale": "ka-GE", "gender": "Male"},
    {"shortName": "de-AT-IngridNeural",         "displayName": "Ingrid Neural",              "locale": "de-AT", "gender": "Female"},
    {"shortName": "de-AT-JonasNeural",          "displayName": "Jonas Neural",               "locale": "de-AT", "gender": "Male"},
    {"shortName": "de-DE-AmalaNeural",          "displayName": "Amala Neural",               "locale": "de-DE", "gender": "Female"},
    {"shortName": "de-DE-ConradNeural",         "displayName": "Conrad Neural",              "locale": "de-DE", "gender": "Male"},
    {"shortName": "de-DE-KatjaNeural",          "displayName": "Katja Neural",               "locale": "de-DE", "gender": "Female"},
    {"shortName": "de-DE-KillianNeural",       "displayName": "Killian Neural",             "locale": "de-DE", "gender": "Male"},
    {"shortName": "de-CH-JanNeural",            "displayName": "Jan Neural",                 "locale": "de-CH", "gender": "Male"},
    {"shortName": "de-CH-LeniNeural",           "displayName": "Leni Neural",                "locale": "de-CH", "gender": "Female"},
    {"shortName": "el-GR-AthinaNeural",         "displayName": "Athina Neural",              "locale": "el-GR", "gender": "Female"},
    {"shortName": "el-GR-NestorasNeural",       "displayName": "Nestoras Neural",            "locale": "el-GR", "gender": "Male"},
    {"shortName": "gu-IN-DhwaniNeural",         "displayName": "Dhwani Neural",              "locale": "gu-IN", "gender": "Female"},
    {"shortName": "gu-IN-NiranjanNeural",       "displayName": "Niranjan Neural",            "locale": "gu-IN", "gender": "Male"},
    {"shortName": "he-IL-AvriNeural",           "displayName": "Avri Neural",                 "locale": "he-IL", "gender": "Male"},
    {"shortName": "he-IL-HilaNeural",           "displayName": "Hila Neural",                 "locale": "he-IL", "gender": "Female"},
    {"shortName": "hi-IN-MadhurNeural",         "displayName": "Madhur Neural",               "locale": "hi-IN", "gender": "Male"},
    {"shortName": "hi-IN-SwaraNeural",          "displayName": "Swara Neural",                "locale": "hi-IN", "gender": "Female"},
    {"shortName": "hu-HU-NoemiNeural",          "displayName": "Noemi Neural",               "locale": "hu-HU", "gender": "Female"},
    {"shortName": "hu-HU-TamasNeural",          "displayName": "Tamas Neural",                "locale": "hu-HU", "gender": "Male"},
    {"shortName": "is-IS-GudrunNeural",         "displayName": "Gudrun Neural",              "locale": "is-IS", "gender": "Female"},
    {"shortName": "is-IS-GunnarNeural",         "displayName": "Gunnar Neural",              "locale": "is-IS", "gender": "Male"},
    {"shortName": "id-ID-ArdiNeural",           "displayName": "Ardi Neural",                 "locale": "id-ID", "gender": "Male"},
    {"shortName": "id-ID-GadisNeural",          "displayName": "Gadis Neural",                "locale": "id-ID", "gender": "Female"},
    {"shortName": "ga-IE-ColmNeural",           "displayName": "Colm Neural",                 "locale": "ga-IE", "gender": "Male"},
    {"shortName": "ga-IE-OrlaNeural",           "displayName": "Orla Neural",                 "locale": "ga-IE", "gender": "Female"},
    {"shortName": "it-IT-DiegoNeural",          "displayName": "Diego Neural",                "locale": "it-IT", "gender": "Male"},
    {"shortName": "it-IT-ElsaNeural",           "displayName": "Elsa Neural",                 "locale": "it-IT", "gender": "Female"},
    {"shortName": "it-IT-IsabellaNeural",       "displayName": "Isabella Neural",             "locale": "it-IT", "gender": "Female"},
    {"shortName": "ja-JP-KeitaNeural",          "displayName": "Keita Neural",                "locale": "ja-JP", "gender": "Male"},
    {"shortName": "ja-JP-NanamiNeural",         "displayName": "Nanami Neural",               "locale": "ja-JP", "gender": "Female"},
    {"shortName": "jv-ID-DimasNeural",          "displayName": "Dimas Neural",                "locale": "jv-ID", "gender": "Male"},
    {"shortName": "jv-ID-SitiNeural",           "displayName": "Siti Neural",                 "locale": "jv-ID", "gender": "Female"},
    {"shortName": "kn-IN-GaganNeural",          "displayName": "Gagan Neural",                "locale": "kn-IN", "gender": "Male"},
    {"shortName": "kn-IN-SapnaNeural",          "displayName": "Sapna Neural",                "locale": "kn-IN", "gender": "Female"},
    {"shortName": "kk-KZ-AigulNeural",          "displayName": "Aigul Neural",                "locale": "kk-KZ", "gender": "Female"},
    {"shortName": "kk-KZ-DauletNeural",         "displayName": "Daulet Neural",               "locale": "kk-KZ", "gender": "Male"},
    {"shortName": "km-KH-PisethNeural",         "displayName": "Piseth Neural",               "locale": "km-KH", "gender": "Male"},
    {"shortName": "km-KH-SreymomNeural",        "displayName": "Sreymom Neural",              "locale": "km-KH", "gender": "Female"},
    {"shortName": "ko-KR-InJoonNeural",         "displayName": "InJoon Neural",               "locale": "ko-KR", "gender": "Male"},
    {"shortName": "ko-KR-SunHiNeural",          "displayName": "SunHi Neural",                "locale": "ko-KR", "gender": "Female"},
    {"shortName": "lo-LA-ChanthavongNeural",    "displayName": "Chanthavong Neural",          "locale": "lo-LA", "gender": "Male"},
    {"shortName": "lo-LA-KeomanyNeural",        "displayName": "Keomany Neural",              "locale": "lo-LA", "gender": "Female"},
    {"shortName": "lv-LV-EveritaNeural",        "displayName": "Everita Neural",              "locale": "lv-LV", "gender": "Female"},
    {"shortName": "lv-LV-NilsNeural",           "displayName": "Nils Neural",                 "locale": "lv-LV", "gender": "Male"},
    {"shortName": "lt-LT-LeonasNeural",         "displayName": "Leonas Neural",               "locale": "lt-LT", "gender": "Male"},
    {"shortName": "lt-LT-OnaNeural",            "displayName": "Ona Neural",                  "locale": "lt-LT", "gender": "Female"},
    {"shortName": "mk-MK-AleksandarNeural",     "displayName": "Aleksandar Neural",           "locale": "mk-MK", "gender": "Male"},
    {"shortName": "mk-MK-MarijaNeural",         "displayName": "Marija Neural",               "locale": "mk-MK", "gender": "Female"},
    {"shortName": "ms-MY-OsmanNeural",          "displayName": "Osman Neural",                "locale": "ms-MY", "gender": "Male"},
    {"shortName": "ms-MY-YasminNeural",         "displayName": "Yasmin Neural",               "locale": "ms-MY", "gender": "Female"},
    {"shortName": "ml-IN-MidhunNeural",         "displayName": "Midhun Neural",               "locale": "ml-IN", "gender": "Male"},
    {"shortName": "ml-IN-SobhanaNeural",        "displayName": "Sobhana Neural",              "locale": "ml-IN", "gender": "Female"},
    {"shortName": "mt-MT-GraceNeural",          "displayName": "Grace Neural",                "locale": "mt-MT", "gender": "Female"},
    {"shortName": "mt-MT-JosephNeural",         "displayName": "Joseph Neural",               "locale": "mt-MT", "gender": "Male"},
    {"shortName": "mr-IN-AarohiNeural",         "displayName": "Aarohi Neural",               "locale": "mr-IN", "gender": "Female"},
    {"shortName": "mr-IN-ManoharNeural",        "displayName": "Manohar Neural",              "locale": "mr-IN", "gender": "Male"},
    {"shortName": "mn-MN-BataaNeural",          "displayName": "Bataa Neural",                "locale": "mn-MN", "gender": "Male"},
    {"shortName": "mn-MN-YesuiNeural",          "displayName": "Yesui Neural",                "locale": "mn-MN", "gender": "Female"},
    {"shortName": "ne-NP-HemkalaNeural",        "displayName": "Hemkala Neural",              "locale": "ne-NP", "gender": "Female"},
    {"shortName": "ne-NP-SagarNeural",          "displayName": "Sagar Neural",                "locale": "ne-NP", "gender": "Male"},
    {"shortName": "nb-NO-FinnNeural",           "displayName": "Finn Neural",                 "locale": "nb-NO", "gender": "Male"},
    {"shortName": "nb-NO-PernilleNeural",       "displayName": "Pernille Neural",             "locale": "nb-NO", "gender": "Female"},
    {"shortName": "ps-AF-GulNawazNeural",       "displayName": "GulNawaz Neural",             "locale": "ps-AF", "gender": "Male"},
    {"shortName": "ps-AF-LatifaNeural",         "displayName": "Latifa Neural",               "locale": "ps-AF", "gender": "Female"},
    {"shortName": "fa-IR-DilaraNeural",         "displayName": "Dilara Neural",               "locale": "fa-IR", "gender": "Female"},
    {"shortName": "fa-IR-FaridNeural",          "displayName": "Farid Neural",                "locale": "fa-IR", "gender": "Male"},
    {"shortName": "pl-PL-MarekNeural",          "displayName": "Marek Neural",                "locale": "pl-PL", "gender": "Male"},
    {"shortName": "pl-PL-ZofiaNeural",          "displayName": "Zofia Neural",                "locale": "pl-PL", "gender": "Female"},
    {"shortName": "pt-BR-AntonioNeural",        "displayName": "Antônio Neural",              "locale": "pt-BR", "gender": "Male"},
    {"shortName": "pt-BR-FranciscaNeural",      "displayName": "Francisca Neural",            "locale": "pt-BR", "gender": "Female"},
    {"shortName": "pt-PT-DuarteNeural",         "displayName": "Duarte Neural",               "locale": "pt-PT", "gender": "Male"},
    {"shortName": "pt-PT-RaquelNeural",         "displayName": "Raquel Neural",               "locale": "pt-PT", "gender": "Female"},
    {"shortName": "ro-RO-AlinaNeural",          "displayName": "Alina Neural",                "locale": "ro-RO", "gender": "Female"},
    {"shortName": "ro-RO-EmilNeural",           "displayName": "Emil Neural",                 "locale": "ro-RO", "gender": "Male"},
    {"shortName": "ru-RU-DmitryNeural",         "displayName": "Dmitry Neural",               "locale": "ru-RU", "gender": "Male"},
    {"shortName": "ru-RU-SvetlanaNeural",       "displayName": "Svetlana Neural",             "locale": "ru-RU", "gender": "Female"},
    {"shortName": "sr-RS-NicholasNeural",       "displayName": "Nicholas Neural",             "locale": "sr-RS", "gender": "Male"},
    {"shortName": "sr-RS-SophieNeural",         "displayName": "Sophie Neural",               "locale": "sr-RS", "gender": "Female"},
    {"shortName": "si-LK-SameeraNeural",        "displayName": "Sameera Neural",              "locale": "si-LK", "gender": "Male"},
    {"shortName": "si-LK-ThiliniNeural",        "displayName": "Thilini Neural",              "locale": "si-LK", "gender": "Female"},
    {"shortName": "sk-SK-LukasNeural",          "displayName": "Lukas Neural",                "locale": "sk-SK", "gender": "Male"},
    {"shortName": "sk-SK-ViktoriaNeural",       "displayName": "Viktoria Neural",             "locale": "sk-SK", "gender": "Female"},
    {"shortName": "sl-SI-PetraNeural",          "displayName": "Petra Neural",                "locale": "sl-SI", "gender": "Female"},
    {"shortName": "sl-SI-RokNeural",            "displayName": "Rok Neural",                  "locale": "sl-SI", "gender": "Male"},
    {"shortName": "so-SO-MuuseNeural",          "displayName": "Muuse Neural",                "locale": "so-SO", "gender": "Male"},
    {"shortName": "so-SO-UbaxNeural",           "displayName": "Ubax Neural",                 "locale": "so-SO", "gender": "Female"},
    {"shortName": "es-AR-ElenaNeural",          "displayName": "Elena Neural",                "locale": "es-AR", "gender": "Female"},
    {"shortName": "es-AR-TomasNeural",          "displayName": "Tomas Neural",                "locale": "es-AR", "gender": "Male"},
    {"shortName": "es-BO-MarceloNeural",        "displayName": "Marcelo Neural",              "locale": "es-BO", "gender": "Male"},
    {"shortName": "es-BO-SofiaNeural",          "displayName": "Sofia Neural",                "locale": "es-BO", "gender": "Female"},
    {"shortName": "es-CL-CatalinaNeural",       "displayName": "Catalina Neural",             "locale": "es-CL", "gender": "Female"},
    {"shortName": "es-CL-LorenzoNeural",        "displayName": "Lorenzo Neural",              "locale": "es-CL", "gender": "Male"},
    {"shortName": "es-CO-GonzaloNeural",        "displayName": "Gonzalo Neural",              "locale": "es-CO", "gender": "Male"},
    {"shortName": "es-CO-SalomeNeural",         "displayName": "Salome Neural",               "locale": "es-CO", "gender": "Female"},
    {"shortName": "es-CR-JuanNeural",           "displayName": "Juan Neural",                 "locale": "es-CR", "gender": "Male"},
    {"shortName": "es-CR-MariaNeural",          "displayName": "Maria Neural",                "locale": "es-CR", "gender": "Female"},
    {"shortName": "es-CU-BelkysNeural",         "displayName": "Belkys Neural",               "locale": "es-CU", "gender": "Female"},
    {"shortName": "es-CU-ManuelNeural",         "displayName": "Manuel Neural",               "locale": "es-CU", "gender": "Male"},
    {"shortName": "es-DO-EmilioNeural",         "displayName": "Emilio Neural",               "locale": "es-DO", "gender": "Male"},
    {"shortName": "es-DO-RamonaNeural",         "displayName": "Ramona Neural",               "locale": "es-DO", "gender": "Female"},
    {"shortName": "es-EC-AndreaNeural",         "displayName": "Andrea Neural",               "locale": "es-EC", "gender": "Female"},
    {"shortName": "es-EC-LuisNeural",           "displayName": "Luis Neural",                 "locale": "es-EC", "gender": "Male"},
    {"shortName": "es-SV-LorenaNeural",         "displayName": "Lorena Neural",               "locale": "es-SV", "gender": "Female"},
    {"shortName": "es-SV-RodrigoNeural",        "displayName": "Rodrigo Neural",              "locale": "es-SV", "gender": "Male"},
    {"shortName": "es-GQ-JavierNeural",         "displayName": "Javier Neural",               "locale": "es-GQ", "gender": "Male"},
    {"shortName": "es-GQ-TeresaNeural",         "displayName": "Teresa Neural",               "locale": "es-GQ", "gender": "Female"},
    {"shortName": "es-GT-AndresNeural",         "displayName": "Andres Neural",               "locale": "es-GT", "gender": "Male"},
    {"shortName": "es-GT-MartaNeural",          "displayName": "Marta Neural",                "locale": "es-GT", "gender": "Female"},
    {"shortName": "es-HN-CarlosNeural",         "displayName": "Carlos Neural",               "locale": "es-HN", "gender": "Male"},
    {"shortName": "es-HN-KarlaNeural",          "displayName": "Karla Neural",                "locale": "es-HN", "gender": "Female"},
    {"shortName": "es-MX-DaliaNeural",          "displayName": "Dalia Neural",                "locale": "es-MX", "gender": "Female"},
    {"shortName": "es-MX-JorgeNeural",          "displayName": "Jorge Neural",                "locale": "es-MX", "gender": "Male"},
    {"shortName": "es-MX-LorenzoEsCLNeural",    "displayName": "LorenzoEsCL Neural",          "locale": "es-MX", "gender": "Male"},
    {"shortName": "es-NI-FedericoNeural",       "displayName": "Federico Neural",             "locale": "es-NI", "gender": "Male"},
    {"shortName": "es-NI-YolandaNeural",        "displayName": "Yolanda Neural",              "locale": "es-NI", "gender": "Female"},
    {"shortName": "es-PA-MargaritaNeural",      "displayName": "Margarita Neural",            "locale": "es-PA", "gender": "Female"},
    {"shortName": "es-PA-RobertoNeural",        "displayName": "Roberto Neural",              "locale": "es-PA", "gender": "Male"},
    {"shortName": "es-PY-MarioNeural",          "displayName": "Mario Neural",                "locale": "es-PY", "gender": "Male"},
    {"shortName": "es-PY-TaniaNeural",          "displayName": "Tania Neural",                "locale": "es-PY", "gender": "Female"},
    {"shortName": "es-PE-AlexNeural",           "displayName": "Alex Neural",                 "locale": "es-PE", "gender": "Male"},
    {"shortName": "es-PE-CamilaNeural",         "displayName": "Camila Neural",               "locale": "es-PE", "gender": "Female"},
    {"shortName": "es-PR-KarinaNeural",         "displayName": "Karina Neural",               "locale": "es-PR", "gender": "Female"},
    {"shortName": "es-PR-VictorNeural",         "displayName": "Victor Neural",               "locale": "es-PR", "gender": "Male"},
    {"shortName": "es-ES-AlvaroNeural",         "displayName": "Álvaro Neural",               "locale": "es-ES", "gender": "Male"},
    {"shortName": "es-ES-ElviraNeural",         "displayName": "Elvira Neural",               "locale": "es-ES", "gender": "Female"},
    {"shortName": "es-ES-ManuelEsCUNeural",     "displayName": "ManuelEsCU Neural",           "locale": "es-ES", "gender": "Male"},
    {"shortName": "es-US-AlonsoNeural",         "displayName": "Alonso Neural",               "locale": "es-US", "gender": "Male"},
    {"shortName": "es-US-PalomaNeural",         "displayName": "Paloma Neural",               "locale": "es-US", "gender": "Female"},
    {"shortName": "es-UY-MateoNeural",          "displayName": "Mateo Neural",                "locale": "es-UY", "gender": "Male"},
    {"shortName": "es-UY-ValentinaNeural",      "displayName": "Valentina Neural",            "locale": "es-UY", "gender": "Female"},
    {"shortName": "es-VE-PaolaNeural",          "displayName": "Paola Neural",                "locale": "es-VE", "gender": "Female"},
    {"shortName": "es-VE-SebastianNeural",      "displayName": "Sebastian Neural",            "locale": "es-VE", "gender": "Male"},
    {"shortName": "su-ID-JajangNeural",         "displayName": "Jajang Neural",               "locale": "su-ID", "gender": "Male"},
    {"shortName": "su-ID-TutiNeural",           "displayName": "Tuti Neural",                 "locale": "su-ID", "gender": "Female"},
    {"shortName": "sw-KE-RafikiNeural",         "displayName": "Rafiki Neural",               "locale": "sw-KE", "gender": "Male"},
    {"shortName": "sw-KE-ZuriNeural",           "displayName": "Zuri Neural",                 "locale": "sw-KE", "gender": "Female"},
    {"shortName": "sw-TZ-DaudiNeural",          "displayName": "Daudi Neural",                "locale": "sw-TZ", "gender": "Male"},
    {"shortName": "sw-TZ-RehemaNeural",         "displayName": "Rehema Neural",               "locale": "sw-TZ", "gender": "Female"},
    {"shortName": "sv-SE-MattiasNeural",        "displayName": "Mattias Neural",              "locale": "sv-SE", "gender": "Male"},
    {"shortName": "sv-SE-SofieNeural",          "displayName": "Sofie Neural",                "locale": "sv-SE", "gender": "Female"},
    {"shortName": "ta-IN-PallaviNeural",        "displayName": "Pallavi Neural",              "locale": "ta-IN", "gender": "Female"},
    {"shortName": "ta-IN-ValluvarNeural",       "displayName": "Valluvar Neural",             "locale": "ta-IN", "gender": "Male"},
    {"shortName": "ta-MY-KaniNeural",           "displayName": "Kani Neural",                 "locale": "ta-MY", "gender": "Female"},
    {"shortName": "ta-MY-SuryaNeural",          "displayName": "Surya Neural",                "locale": "ta-MY", "gender": "Male"},
    {"shortName": "ta-SG-AnbuNeural",           "displayName": "Anbu Neural",                 "locale": "ta-SG", "gender": "Male"},
    {"shortName": "ta-SG-VenbaNeural",          "displayName": "Venba Neural",                "locale": "ta-SG", "gender": "Female"},
    {"shortName": "ta-LK-KumarNeural",          "displayName": "Kumar Neural",                "locale": "ta-LK", "gender": "Male"},
    {"shortName": "ta-LK-SaranyaNeural",        "displayName": "Saranya Neural",              "locale": "ta-LK", "gender": "Female"},
    {"shortName": "te-IN-MohanNeural",          "displayName": "Mohan Neural",                "locale": "te-IN", "gender": "Male"},
    {"shortName": "te-IN-ShrutiNeural",         "displayName": "Shruti Neural",               "locale": "te-IN", "gender": "Female"},
    {"shortName": "th-TH-NiwatNeural",          "displayName": "Niwat Neural",                "locale": "th-TH", "gender": "Male"},
    {"shortName": "th-TH-PremwadeeNeural",      "displayName": "Premwadee Neural",            "locale": "th-TH", "gender": "Female"},
    {"shortName": "tr-TR-AhmetNeural",          "displayName": "Ahmet Neural",                "locale": "tr-TR", "gender": "Male"},
    {"shortName": "tr-TR-EmelNeural",           "displayName": "Emel Neural",                 "locale": "tr-TR", "gender": "Female"},
    {"shortName": "uk-UA-OstapNeural",          "displayName": "Ostap Neural",                "locale": "uk-UA", "gender": "Male"},
    {"shortName": "uk-UA-PolinaNeural",         "displayName": "Polina Neural",               "locale": "uk-UA", "gender": "Female"},
    {"shortName": "ur-IN-GulNeural",            "displayName": "Gul Neural",                  "locale": "ur-IN", "gender": "Female"},
    {"shortName": "ur-IN-SalmanNeural",         "displayName": "Salman Neural",               "locale": "ur-IN", "gender": "Male"},
    {"shortName": "ur-PK-AsadNeural",           "displayName": "Asad Neural",                 "locale": "ur-PK", "gender": "Male"},
    {"shortName": "ur-PK-UzmaNeural",           "displayName": "Uzma Neural",                 "locale": "ur-PK", "gender": "Female"},
    {"shortName": "uz-UZ-MadinaNeural",         "displayName": "Madina Neural",               "locale": "uz-UZ", "gender": "Female"},
    {"shortName": "uz-UZ-SardorNeural",         "displayName": "Sardor Neural",               "locale": "uz-UZ", "gender": "Male"},
    {"shortName": "vi-VN-HoaiMyNeural",         "displayName": "HoaiMy Neural",               "locale": "vi-VN", "gender": "Female"},
    {"shortName": "vi-VN-NamMinhNeural",        "displayName": "NamMinh Neural",              "locale": "vi-VN", "gender": "Male"},
    {"shortName": "cy-GB-AledNeural",           "displayName": "Aled Neural",                 "locale": "cy-GB", "gender": "Male"},
    {"shortName": "cy-GB-NiaNeural",            "displayName": "Nia Neural",                  "locale": "cy-GB", "gender": "Female"},
    {"shortName": "zu-ZA-ThandoNeural",         "displayName": "Thando Neural",               "locale": "zu-ZA", "gender": "Female"},
    {"shortName": "zu-ZA-ThembaNeural",         "displayName": "Themba Neural",               "locale": "zu-ZA", "gender": "Male"},
]


def _load_from_json() -> Optional[List[Dict]]:
    if VOICES_JSON_PATH.exists():
        try:
            return json.loads(VOICES_JSON_PATH.read_text(encoding="utf-8"))
        except Exception:
            return None
    return None

def load_voices() -> List[Dict]:
    """
    Carrega as vozes a partir do voices.json (se existir),
    senão usa o STATIC_VOICES.
    """
    data = _load_from_json()
    if isinstance(data, list) and data:
        return data
    return STATIC_VOICES

def voices_for_lang(lang_code: str) -> List[Dict]:
    """
    Retorna todas as vozes cujo locale começa com o idioma detectado.
    Ex.: lang_code='pt' -> ['pt-BR-...', 'pt-PT-...'].
    """
    if not lang_code:
        return []
    lang = lang_code.split("-")[0].lower()  # 'pt'
    voices = load_voices()
    result = [v for v in voices if v.get("locale", "").lower().startswith(f"{lang}-")]
    # Ordena por locale e nome amigável
    result.sort(key=lambda v: (v.get("locale", ""), v.get("displayName") or v.get("shortName")))
    return result

def default_voice_for_lang(lang_code: str, prefer_gender: Optional[str] = None) -> Optional[str]:
    """
    Escolhe uma voz padrão para o idioma detectado.
    prefer_gender: 'Male' | 'Female' | None
    """
    candidates = voices_for_lang(lang_code)
    if not candidates:
        return None
    if prefer_gender:
        for v in candidates:
            if v.get("gender") == prefer_gender:
                return v["shortName"]
    # fallback: primeira da lista
    return candidates[0]["shortName"]

def as_public_voice(v: Dict) -> Dict:
    """Mapeia para o formato enxuto que vamos expor no JSON da API."""
    return {
        "shortName": v.get("shortName"),
        "displayName": v.get("displayName") or v.get("shortName"),
        "locale": v.get("locale"),
        "gender": v.get("gender"),
    }
